// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: chat/chat_message.proto

package chat

import (
	common "game-protocols/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest_MessageType int32

const (
	ChatRequest_TEXT       ChatRequest_MessageType = 0 // 纯文本
	ChatRequest_EMOJI      ChatRequest_MessageType = 1 // 表情
	ChatRequest_ITEM       ChatRequest_MessageType = 2 // 道具
	ChatRequest_COORDINATE ChatRequest_MessageType = 3 // 坐标
)

// Enum value maps for ChatRequest_MessageType.
var (
	ChatRequest_MessageType_name = map[int32]string{
		0: "TEXT",
		1: "EMOJI",
		2: "ITEM",
		3: "COORDINATE",
	}
	ChatRequest_MessageType_value = map[string]int32{
		"TEXT":       0,
		"EMOJI":      1,
		"ITEM":       2,
		"COORDINATE": 3,
	}
)

func (x ChatRequest_MessageType) Enum() *ChatRequest_MessageType {
	p := new(ChatRequest_MessageType)
	*p = x
	return p
}

func (x ChatRequest_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatRequest_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_chat_message_proto_enumTypes[0].Descriptor()
}

func (ChatRequest_MessageType) Type() protoreflect.EnumType {
	return &file_chat_chat_message_proto_enumTypes[0]
}

func (x ChatRequest_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatRequest_MessageType.Descriptor instead.
func (ChatRequest_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_chat_chat_message_proto_rawDescGZIP(), []int{0, 0}
}

type ChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1. 核心字段（必须）
	Base *common.MessageBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// 2. 业务特定字段
	ReceiverId int32                   `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // 私聊接收者（0 表示频道消息）
	ChannelId  int32                   `protobuf:"varint,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`    // 频道 ID（0 表示私聊）
	Type       ChatRequest_MessageType `protobuf:"varint,4,opt,name=type,proto3,enum=chat.ChatRequest_MessageType" json:"type,omitempty"`
	Content    string                  `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ExtraData  []byte                  `protobuf:"bytes,6,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"` // 附加数据（如道具信息）
	// 3. 可选扩展元数据（按需使用，大部分情况下为空）
	// 用途：需要追踪、版本控制时才填充
	Meta          *common.MessageMeta `protobuf:"bytes,10,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_chat_chat_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_message_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetBase() *common.MessageBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ChatRequest) GetReceiverId() int32 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *ChatRequest) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ChatRequest) GetType() ChatRequest_MessageType {
	if x != nil {
		return x.Type
	}
	return ChatRequest_TEXT
}

func (x *ChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatRequest) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *ChatRequest) GetMeta() *common.MessageMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ChatResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Base         *common.MessageBase    `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Success      bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	MessageId    int64                  `protobuf:"varint,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 消息在 DB 中的唯一 ID
	Timestamp    int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 路由信息 (用于 Gateway 转发)
	TargetUserId    int32  `protobuf:"varint,10,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`         // 目标用户 ID (优先使用)
	TargetSessionId string `protobuf:"bytes,11,opt,name=target_session_id,json=targetSessionId,proto3" json:"target_session_id,omitempty"` // 或目标 Session ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_chat_chat_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_message_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetBase() *common.MessageBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ChatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChatResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ChatResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ChatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ChatResponse) GetTargetUserId() int32 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *ChatResponse) GetTargetSessionId() string {
	if x != nil {
		return x.TargetSessionId
	}
	return ""
}

type MessageBroadcast struct {
	state      protoimpl.MessageState  `protogen:"open.v1"`
	MessageId  int64                   `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId   int32                   `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderName string                  `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	ChannelId  int32                   `protobuf:"varint,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content    string                  `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp  int64                   `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type       ChatRequest_MessageType `protobuf:"varint,7,opt,name=type,proto3,enum=chat.ChatRequest_MessageType" json:"type,omitempty"`
	// 路由信息 (用于 Gateway 转发)
	TargetUserId  int32 `protobuf:"varint,10,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"` // 目标用户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBroadcast) Reset() {
	*x = MessageBroadcast{}
	mi := &file_chat_chat_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBroadcast) ProtoMessage() {}

func (x *MessageBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBroadcast.ProtoReflect.Descriptor instead.
func (*MessageBroadcast) Descriptor() ([]byte, []int) {
	return file_chat_chat_message_proto_rawDescGZIP(), []int{2}
}

func (x *MessageBroadcast) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageBroadcast) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MessageBroadcast) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *MessageBroadcast) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *MessageBroadcast) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageBroadcast) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageBroadcast) GetType() ChatRequest_MessageType {
	if x != nil {
		return x.Type
	}
	return ChatRequest_TEXT
}

func (x *MessageBroadcast) GetTargetUserId() int32 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

var File_chat_chat_message_proto protoreflect.FileDescriptor

const file_chat_chat_message_proto_rawDesc = "" +
	"\n" +
	"\x17chat/chat_message.proto\x12\x04chat\x1a\x19common/message_base.proto\"\xc9\x02\n" +
	"\vChatRequest\x12'\n" +
	"\x04base\x18\x01 \x01(\v2\x13.common.MessageBaseR\x04base\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\x05R\n" +
	"receiverId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\x05R\tchannelId\x121\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1d.chat.ChatRequest.MessageTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"extra_data\x18\x06 \x01(\fR\textraData\x12'\n" +
	"\x04meta\x18\n" +
	" \x01(\v2\x13.common.MessageMetaR\x04meta\"<\n" +
	"\vMessageType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\t\n" +
	"\x05EMOJI\x10\x01\x12\b\n" +
	"\x04ITEM\x10\x02\x12\x0e\n" +
	"\n" +
	"COORDINATE\x10\x03\"\x85\x02\n" +
	"\fChatResponse\x12'\n" +
	"\x04base\x18\x01 \x01(\v2\x13.common.MessageBaseR\x04base\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\x03R\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12$\n" +
	"\x0etarget_user_id\x18\n" +
	" \x01(\x05R\ftargetUserId\x12*\n" +
	"\x11target_session_id\x18\v \x01(\tR\x0ftargetSessionId\"\x9f\x02\n" +
	"\x10MessageBroadcast\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x05R\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x03 \x01(\tR\n" +
	"senderName\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\x05R\tchannelId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x121\n" +
	"\x04type\x18\a \x01(\x0e2\x1d.chat.ChatRequest.MessageTypeR\x04type\x12$\n" +
	"\x0etarget_user_id\x18\n" +
	" \x01(\x05R\ftargetUserIdB\x15Z\x13game-protocols/chatb\x06proto3"

var (
	file_chat_chat_message_proto_rawDescOnce sync.Once
	file_chat_chat_message_proto_rawDescData []byte
)

func file_chat_chat_message_proto_rawDescGZIP() []byte {
	file_chat_chat_message_proto_rawDescOnce.Do(func() {
		file_chat_chat_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_chat_message_proto_rawDesc), len(file_chat_chat_message_proto_rawDesc)))
	})
	return file_chat_chat_message_proto_rawDescData
}

var file_chat_chat_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_chat_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chat_chat_message_proto_goTypes = []any{
	(ChatRequest_MessageType)(0), // 0: chat.ChatRequest.MessageType
	(*ChatRequest)(nil),          // 1: chat.ChatRequest
	(*ChatResponse)(nil),         // 2: chat.ChatResponse
	(*MessageBroadcast)(nil),     // 3: chat.MessageBroadcast
	(*common.MessageBase)(nil),   // 4: common.MessageBase
	(*common.MessageMeta)(nil),   // 5: common.MessageMeta
}
var file_chat_chat_message_proto_depIdxs = []int32{
	4, // 0: chat.ChatRequest.base:type_name -> common.MessageBase
	0, // 1: chat.ChatRequest.type:type_name -> chat.ChatRequest.MessageType
	5, // 2: chat.ChatRequest.meta:type_name -> common.MessageMeta
	4, // 3: chat.ChatResponse.base:type_name -> common.MessageBase
	0, // 4: chat.MessageBroadcast.type:type_name -> chat.ChatRequest.MessageType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_chat_chat_message_proto_init() }
func file_chat_chat_message_proto_init() {
	if File_chat_chat_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_chat_message_proto_rawDesc), len(file_chat_chat_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_chat_message_proto_goTypes,
		DependencyIndexes: file_chat_chat_message_proto_depIdxs,
		EnumInfos:         file_chat_chat_message_proto_enumTypes,
		MessageInfos:      file_chat_chat_message_proto_msgTypes,
	}.Build()
	File_chat_chat_message_proto = out.File
	file_chat_chat_message_proto_goTypes = nil
	file_chat_chat_message_proto_depIdxs = nil
}
