// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: chat/chat_service.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokenRequest) Reset() {
	*x = AuthTokenRequest{}
	mi := &file_chat_chat_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenRequest) ProtoMessage() {}

func (x *AuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenRequest.ProtoReflect.Descriptor instead.
func (*AuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{0}
}

func (x *AuthTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Valid         bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdentity) Reset() {
	*x = UserIdentity{}
	mi := &file_chat_chat_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentity) ProtoMessage() {}

func (x *UserIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentity.ProtoReflect.Descriptor instead.
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserIdentity) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserIdentity) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *UserIdentity) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type SystemBroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	TargetUsers   []int32                `protobuf:"varint,2,rep,packed,name=target_users,json=targetUsers,proto3" json:"target_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemBroadcastRequest) Reset() {
	*x = SystemBroadcastRequest{}
	mi := &file_chat_chat_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemBroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemBroadcastRequest) ProtoMessage() {}

func (x *SystemBroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemBroadcastRequest.ProtoReflect.Descriptor instead.
func (*SystemBroadcastRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{2}
}

func (x *SystemBroadcastRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SystemBroadcastRequest) GetTargetUsers() []int32 {
	if x != nil {
		return x.TargetUsers
	}
	return nil
}

type KickUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserRequest) Reset() {
	*x = KickUserRequest{}
	mi := &file_chat_chat_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserRequest) ProtoMessage() {}

func (x *KickUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserRequest.ProtoReflect.Descriptor instead.
func (*KickUserRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{3}
}

func (x *KickUserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *KickUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_chat_chat_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_proto_rawDescGZIP(), []int{4}
}

var File_chat_chat_service_proto protoreflect.FileDescriptor

const file_chat_chat_service_proto_rawDesc = "" +
	"\n" +
	"\x17chat/chat_service.proto\x12\x04chat\"(\n" +
	"\x10AuthTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"V\n" +
	"\fUserIdentity\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\tR\x06gameId\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\"U\n" +
	"\x16SystemBroadcastRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12!\n" +
	"\ftarget_users\x18\x02 \x03(\x05R\vtargetUsers\"B\n" +
	"\x0fKickUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\a\n" +
	"\x05Empty2\xc0\x01\n" +
	"\vChatService\x12?\n" +
	"\x11ValidateAuthToken\x12\x16.chat.AuthTokenRequest\x1a\x12.chat.UserIdentity\x12@\n" +
	"\x13SendSystemBroadcast\x12\x1c.chat.SystemBroadcastRequest\x1a\v.chat.Empty\x12.\n" +
	"\bKickUser\x12\x15.chat.KickUserRequest\x1a\v.chat.EmptyB\x15Z\x13game-protocols/chatb\x06proto3"

var (
	file_chat_chat_service_proto_rawDescOnce sync.Once
	file_chat_chat_service_proto_rawDescData []byte
)

func file_chat_chat_service_proto_rawDescGZIP() []byte {
	file_chat_chat_service_proto_rawDescOnce.Do(func() {
		file_chat_chat_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_chat_service_proto_rawDesc), len(file_chat_chat_service_proto_rawDesc)))
	})
	return file_chat_chat_service_proto_rawDescData
}

var file_chat_chat_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chat_chat_service_proto_goTypes = []any{
	(*AuthTokenRequest)(nil),       // 0: chat.AuthTokenRequest
	(*UserIdentity)(nil),           // 1: chat.UserIdentity
	(*SystemBroadcastRequest)(nil), // 2: chat.SystemBroadcastRequest
	(*KickUserRequest)(nil),        // 3: chat.KickUserRequest
	(*Empty)(nil),                  // 4: chat.Empty
}
var file_chat_chat_service_proto_depIdxs = []int32{
	0, // 0: chat.ChatService.ValidateAuthToken:input_type -> chat.AuthTokenRequest
	2, // 1: chat.ChatService.SendSystemBroadcast:input_type -> chat.SystemBroadcastRequest
	3, // 2: chat.ChatService.KickUser:input_type -> chat.KickUserRequest
	1, // 3: chat.ChatService.ValidateAuthToken:output_type -> chat.UserIdentity
	4, // 4: chat.ChatService.SendSystemBroadcast:output_type -> chat.Empty
	4, // 5: chat.ChatService.KickUser:output_type -> chat.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat_chat_service_proto_init() }
func file_chat_chat_service_proto_init() {
	if File_chat_chat_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_chat_service_proto_rawDesc), len(file_chat_chat_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_chat_service_proto_goTypes,
		DependencyIndexes: file_chat_chat_service_proto_depIdxs,
		MessageInfos:      file_chat_chat_service_proto_msgTypes,
	}.Build()
	File_chat_chat_service_proto = out.File
	file_chat_chat_service_proto_goTypes = nil
	file_chat_chat_service_proto_depIdxs = nil
}
