// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: common/message_base.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 所有业务消息的基类
type MessageBase struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 游戏标识（用于多游戏隔离）
	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"` // 例如: "game_mmo", "game_card", "game_moba"
	// 用户标识
	UserId int32 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 发送者用户 ID
	// 消息元数据
	Timestamp     int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // 客户端时间戳
	ClientVersion string `protobuf:"bytes,4,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"` // 客户端版本（用于兼容性检查）
	DeviceId      string `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                // 设备 ID（可选，用于多端登录检测）
	// 追踪与调试
	TraceId       string `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`       // 分布式追踪 ID
	SessionId     string `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBase) Reset() {
	*x = MessageBase{}
	mi := &file_common_message_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBase) ProtoMessage() {}

func (x *MessageBase) ProtoReflect() protoreflect.Message {
	mi := &file_common_message_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBase.ProtoReflect.Descriptor instead.
func (*MessageBase) Descriptor() ([]byte, []int) {
	return file_common_message_base_proto_rawDescGZIP(), []int{0}
}

func (x *MessageBase) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MessageBase) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageBase) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageBase) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *MessageBase) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *MessageBase) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *MessageBase) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_common_message_base_proto protoreflect.FileDescriptor

const file_common_message_base_proto_rawDesc = "" +
	"\n" +
	"\x19common/message_base.proto\x12\x06common\"\xdb\x01\n" +
	"\vMessageBase\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0eclient_version\x18\x04 \x01(\tR\rclientVersion\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionIdB\x17Z\x15game-protocols/commonb\x06proto3"

var (
	file_common_message_base_proto_rawDescOnce sync.Once
	file_common_message_base_proto_rawDescData []byte
)

func file_common_message_base_proto_rawDescGZIP() []byte {
	file_common_message_base_proto_rawDescOnce.Do(func() {
		file_common_message_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_message_base_proto_rawDesc), len(file_common_message_base_proto_rawDesc)))
	})
	return file_common_message_base_proto_rawDescData
}

var file_common_message_base_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_message_base_proto_goTypes = []any{
	(*MessageBase)(nil), // 0: common.MessageBase
}
var file_common_message_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_message_base_proto_init() }
func file_common_message_base_proto_init() {
	if File_common_message_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_message_base_proto_rawDesc), len(file_common_message_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_message_base_proto_goTypes,
		DependencyIndexes: file_common_message_base_proto_depIdxs,
		MessageInfos:      file_common_message_base_proto_msgTypes,
	}.Build()
	File_common_message_base_proto = out.File
	file_common_message_base_proto_goTypes = nil
	file_common_message_base_proto_depIdxs = nil
}
